# Generated by Django 4.1 on 2022-08-24 09:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blogs'),
            preserve_default=False,
        ),
    ]
