# Generated by Django 4.1 on 2022-08-24 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_blogmodel_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blogs.appuser'),
        ),
    ]
