# Generated by Django 4.1 on 2022-08-30 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_person_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book',
            new_name='person',
        ),
    ]
